version: '3.8'

services:
  # MySQL Database for Game Service
  mysql_game:
    image: mysql:8.0
    container_name: mysql_game
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1111'  # Root password
      MYSQL_DATABASE: 'game_db'  # The database to be created for game service
    volumes:
      - mysql_game_data:/var/lib/mysql
    networks:
      - app_network

  # Redis Service
  redis:
    image: redis:latest  # Use the lightweight Alpine version of Redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"  # Map host port 6379 to container port 6379
    networks:
      - app_network

  # First Flask game service instance
  game_service_1:
    build:
      context: .  # Use the current directory to build the image
    depends_on:
      - mysql_game  # Ensure MySQL starts before the game service
    networks:
      - app_network

# Define the shared network
networks:
  app_network:
    driver: bridge

# Define named volumes for the MySQL data
volumes:
  mysql_game_data: